# Generated by hand (see EMAIL_SETUP.md) — mirrors what
# `python manage.py makemigrations` would produce for the model changes in
# accounts/models.py (PendingSignup + EmailOTP.Meta.constraints).
#
# NOTE for deployments with existing data: AddConstraint will fail if any
# (email, purpose) pair currently has more than one EmailOTP row. Before
# running this migration against a populated database, dedupe first, e.g.:
#
#   from accounts.models import EmailOTP
#   from django.db.models import Count
#   dupes = (EmailOTP.objects.values("email", "purpose")
#            .annotate(c=Count("id")).filter(c__gt=1))
#   for d in dupes:
#       rows = EmailOTP.objects.filter(email=d["email"], purpose=d["purpose"]).order_by("-created_at")
#       for stale in rows[1:]:
#           stale.delete()

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp_attempts_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(
                fields=('email', 'purpose'),
                name='accounts_emailotp_one_active_per_email_purpose',
            ),
        ),
    ]
