# Generated by Django 5.2 on 2026-08-13 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingsignup_emailotp_unique_email_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('reserved_balance', models.PositiveBigIntegerField(default=0)),
                ('lifetime_earned', models.PositiveBigIntegerField(default=0)),
                ('lifetime_used', models.PositiveBigIntegerField(default=0)),
                ('last_monthly_grant_period', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('feature', models.CharField(default='chat', max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_unavailable', models.BooleanField(default=False)),
                ('credits_reserved', models.PositiveIntegerField(default=0)),
                ('credits_charged', models.PositiveIntegerField(default=0)),
                ('credits_refunded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('VALIDATION_FAILURE', 'Validation Failure'), ('INSUFFICIENT_CREDITS', 'Insufficient Credits'), ('RESERVED', 'Reserved'), ('PROVIDER_SUCCESS', 'Provider Success'), ('PROVIDER_FAILURE', 'Provider Failure'), ('TIMEOUT', 'Timeout'), ('MALFORMED_RESPONSE', 'Malformed Response'), ('FINALIZED', 'Finalized'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to='accounts.creditaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('GRANT', 'Grant'), ('BONUS', 'Bonus'), ('RESERVE', 'Reserve'), ('USAGE', 'Usage'), ('REFUND', 'Refund'), ('EXPIRATION', 'Expiration'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_before', models.PositiveBigIntegerField()),
                ('balance_after', models.PositiveBigIntegerField()),
                ('reserved_before', models.PositiveBigIntegerField()),
                ('reserved_after', models.PositiveBigIntegerField()),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.creditaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['guest_session_key'], name='accounts_cr_guest_s_d11b50_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_session_key__isnull', True), ('user__isnull', False)), models.Q(('guest_session_key__isnull', False), ('user__isnull', True)), _connector='OR'), name='ck_creditaccount_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ck_creditaccount_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__gte', 0)), name='ck_creditaccount_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', models.F('reserved_balance'))), name='ck_creditaccount_balance_gte_reserved'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ai_user_id_390961_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['guest_session_key', '-created_at'], name='accounts_ai_guest_s_b518a7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['status'], name='accounts_ai_status_9a346d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['request_id'], name='accounts_ai_request_5e48bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_session_key', ''), ('user__isnull', False)), models.Q(('user__isnull', True), models.Q(('guest_session_key', ''), _negated=True)), _connector='OR'), name='ck_aiusage_user_or_guest'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='accounts_cr_user_id_764de8_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_account', '-created_at'], name='accounts_cr_credit__542c80_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['reference_id'], name='accounts_cr_referen_9e837f_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='accounts_cr_transac_7e43ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0)), name='ck_credittxn_bal_before_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='ck_credittxn_bal_after_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_before__gte', 0)), name='ck_credittxn_res_before_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_after__gte', 0)), name='ck_credittxn_res_after_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__gt', '')), fields=('credit_account', 'reference_id', 'transaction_type'), name='uq_credittxn_account_reference_type'),
        ),
    ]
