# Generated by Django 5.2 on 2026-08-13 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_credit_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('AI_GENERATOR', 'AI Generator')], default='AI_GENERATOR', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitlements', to='accounts.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntitlementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANT', 'Grant'), ('REVOKE', 'Revoke'), ('SUSPEND', 'Suspend'), ('REACTIVATE', 'Reactivate'), ('EXTEND', 'Extend')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_actions', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.userentitlement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeatureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('ALLOWED', 'Allowed'), ('DISABLED', 'Disabled')], default='ALLOWED', max_length=20)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_request_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_rules', to='accounts.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_rules', to='accounts.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'feature'], name='accounts_pl_plan_id_6e73f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='uq_planfeaturerule_plan_feature')],
            },
        ),
        migrations.AddIndex(
            model_name='userentitlement',
            index=models.Index(fields=['user', 'status'], name='accounts_us_user_id_847f67_idx'),
        ),
        migrations.AddIndex(
            model_name='userentitlement',
            index=models.Index(fields=['plan', 'status'], name='accounts_us_plan_id_c9fb62_idx'),
        ),
        migrations.AddIndex(
            model_name='userentitlement',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_a81551_idx'),
        ),
        migrations.AddConstraint(
            model_name='userentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('starts_at')), _connector='OR'), name='ck_userentitlement_expires_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='userentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'plan'), name='uq_userentitlement_one_active_per_user_plan'),
        ),
        migrations.AddIndex(
            model_name='entitlementauditlog',
            index=models.Index(fields=['entitlement', '-created_at'], name='accounts_en_entitle_c69ba5_idx'),
        ),
    ]
