# Generated by Django 5.2 on 2026-08-14 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscription_subscriptionauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_id'], name='accounts_pr_provide_af2b1c_idx'), models.Index(fields=['status'], name='accounts_pr_status_21b469_idx'), models.Index(fields=['-received_at'], name='accounts_pr_receive_8ee26f_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uq_providerevent_provider_event_id')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('provider', models.CharField(default='razorpay', max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_937032_idx'), models.Index(fields=['status'], name='accounts_pa_status_8957e4_idx'), models.Index(fields=['provider', 'order_id'], name='accounts_pa_provide_06c90d_idx'), models.Index(fields=['provider', 'payment_id'], name='accounts_pa_provide_2657d0_idx'), models.Index(fields=['subscription'], name='accounts_pa_subscri_bc0df4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order_id__isnull', False)), fields=('provider', 'order_id'), name='uq_payment_provider_order_id'), models.UniqueConstraint(condition=models.Q(('payment_id__isnull', False)), fields=('provider', 'payment_id'), name='uq_payment_provider_payment_id'), models.UniqueConstraint(condition=models.Q(('status', 'CREATED')), fields=('user',), name='uq_payment_one_created_per_user'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_gt_0'), models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED'])), name='ck_payment_valid_status'), models.CheckConstraint(condition=models.Q(('billing_interval__in', ['MONTHLY', 'YEARLY'])), name='ck_payment_valid_billing_interval')],
            },
        ),
    ]
