# Generated by Django 5.2 on 2026-08-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_photo_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='feature',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('code', 'Code'), ('story', 'Story'), ('application', 'Application'), ('proposal', 'Proposal'), ('photo', 'Photo')], default='', max_length=20),
        ),
    ]
