# Generated by Django 5.2 on 2026-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chathistory_add_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
