# Generated by Django 5.2 on 2026-08-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_chathistory_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('GRANT', 'Grant'), ('BONUS', 'Bonus'), ('RESERVE', 'Reserve'), ('USAGE', 'Usage'), ('REFUND', 'Refund'), ('EXPIRATION', 'Expiration'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('MIGRATION', 'Migration')], max_length=20),
        ),
    ]
